### ISSUE TITLE
[bug, strikes] Some Buttons: Indicator rule checking for incorrect indicator 

### ISSUE THREAD

**Issue by Kodipher** [SegaSaturnity/KtaneMaelztromMaeldulos#1]
## The issue
The second rule in the manual (The bomb has a lit FRK indicator) operates incorrectly: lit FRK
indicator was present, despite that the last button struck.

## Log:
![image](https://github.com/SegaSaturnity/KtaneMaelztromMaeldulos/assets/45706822/3946e7f0-ac37-41cc-af34-f8a34deb8c40)
Ruleseed was disabled.

#### Assumption:
The module is checking for lit indicator NLL instead

**Comment by SegaSaturnity** [comment]
Fixed on 1538369. It was exactly that, should be checking FRK correctly now.

Thanks for the heads-up.
